version: "3.0"
services:
  db:
    image: "postgres:9.4"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - result-tier
      - back-tier
    restart: on-failure

  redis:
    image: "redis:alpine"
    expose:
      - "6379"
    networks:
      - poll-tier
      - back-tier
    restart: on-failure

  poll:
    build: ./poll
    ports:
      - "5000:80"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - "redis"
    networks:
      - poll-tier
    restart: on-failure

  result:
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    build: ./result
    command: node server.js
    ports:
      - "5001:80"
    depends_on:
      - "db"
    networks:
      - result-tier
    restart: on-failure

  worker:
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - REDIS_HOST=redis
    build:
      context: ./worker
    depends_on:
      - "db"
      - "redis"
    networks:
      - back-tier
    restart: on-failure

volumes:
  db-data:

networks:
  poll-tier:
  result-tier:
  back-tier: